#!/usr/bin/env sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
OUT_DIR="$ROOT/build"
PLUGIN_NAME="PongQuestExample"
SOURCE_PLUGIN="$ROOT/overlay/js/plugins/$PLUGIN_NAME.js"
INPUT_DIR="${1:-${RPGMAKER_WEB_BUILD:-}}"

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

require_dir() {
  [ -d "$1" ] || die "Unable to find $2 at $1."
}

require_file() {
  [ -f "$1" ] || die "Expected $2 at $1."
}

if [ -z "$INPUT_DIR" ]; then
  die "Set RPGMAKER_WEB_BUILD to an RPG Maker MZ web deployment directory, or pass it as the first argument."
fi

require_dir "$INPUT_DIR" "RPG Maker web deployment"
require_file "$INPUT_DIR/index.html" "index.html"
require_file "$INPUT_DIR/js/plugins.js" "js/plugins.js"
require_file "$INPUT_DIR/js/main.js" "js/main.js"
require_file "$SOURCE_PLUGIN" "source plugin"

if ! command -v python3 >/dev/null 2>&1; then
  die "python3 is required to patch js/plugins.js."
fi

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
cp -R "$INPUT_DIR"/. "$OUT_DIR/"

mkdir -p "$OUT_DIR/js/plugins"
cp "$SOURCE_PLUGIN" "$OUT_DIR/js/plugins/$PLUGIN_NAME.js"

python3 - "$OUT_DIR/js/plugins.js" "$PLUGIN_NAME" <<'PY'
import json
import pathlib
import sys

plugins_path = pathlib.Path(sys.argv[1])
plugin_name = sys.argv[2]
text = plugins_path.read_text(encoding="utf-8")
start = text.find("[")
end = text.rfind("]")

if start == -1 or end == -1 or end < start:
    raise SystemExit(f"Unable to parse plugin list in {plugins_path}.")

plugins = json.loads(text[start : end + 1])
entry = {
    "name": plugin_name,
    "status": True,
    "description": "Pong Quest demo with Wavedash integration for RPG Maker MZ web exports.",
    "parameters": {},
}

for plugin in plugins:
    if plugin.get("name") == entry["name"]:
        plugin.update(entry)
        break
else:
    plugins.append(entry)

plugins_path.write_text(
    "// Generated by RPG Maker.\n"
    "// Do not edit this file directly.\n"
    "var $plugins =\n"
    + json.dumps(plugins, indent=4)
    + ";\n",
    encoding="utf-8",
)
PY

printf '%s\n' "Built Pong Quest example in $OUT_DIR"
